name: hello-world
'on': push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
        run: .\tosca_execution_client.ps1 -toscaServerUrl <toscaServerUrl> -projectName <projectName> -events <events>
