name: hello-world
'on': push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: my-step
       
        shell: cmd        
        run: testmo automation:run:submit --instance https://legogroup.testmo.net --project-id 26 --name "Tosca run" --source "Regression" --results c:\Tesmoresult.xml
        
